# Generated by Django 5.1.6 on 2025-07-05 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventory_image_inventorycategory_image'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('l', 'Liters'), ('pcs', 'Pieces')], default='g', max_length=10)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_recipes', to='inventory.inventory')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_ingredients', to='items.item')),
            ],
            options={
                'db_table': 'item_ingredients',
                'unique_together': {('item', 'inventory')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='ingredients',
            field=models.ManyToManyField(related_name='items', through='items.ItemIngredient', to='inventory.inventory'),
        ),
    ]
