# Generated by Django 5.1.6 on 2025-07-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventory_image_inventorycategory_image'),
        ('items', '0002_itemingredient_item_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemingredient',
            old_name='inventory',
            new_name='ingredients',
        ),
        migrations.AlterUniqueTogether(
            name='itemingredient',
            unique_together={('item', 'ingredients')},
        ),
    ]
