# Generated by Django 5.1.6 on 2025-04-20 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorycategory_branch'),
        ('restaurants', '0004_remove_branch_branch_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='branch',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='restaurants.branch'),
            preserve_default=False,
        ),
    ]
