# Generated by Django 5.1.6 on 2025-04-20 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_supplier_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.RenameIndex(
            model_name='inventory',
            new_name='idx_inventory_branch',
            old_name='idx_inventory_branch_id',
        ),
    ]
