# Generated by Django 5.1.6 on 2025-04-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_cost_alter_inventory_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='branch_id',
            new_name='branch',
        ),
    ]
