# Generated by Django 5.1.6 on 2025-05-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventorytransaction_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory_items/'),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory_categories/'),
        ),
    ]
