# Generated by Django 5.1.6 on 2025-08-19 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
        ('restaurants', '0007_alter_branch_operating_hours_alter_branch_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('order_id', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('notification_type', models.CharField(choices=[('order_update', 'Order Update'), ('delay_alert', 'Delay Alert'), ('staff_assignment', 'Staff Assignment'), ('system_alert', 'System Alert')], default='order_update', max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_notifications', to='restaurants.branch')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['branch', 'is_read'], name='kitchen_kit_branch__a7059c_idx'), models.Index(fields=['created_at'], name='kitchen_kit_created_f0e473_idx')],
            },
        ),
    ]
