# Generated by Django 5.1.6 on 2025-04-18 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_branchowner_idx_branchowners_restaurant_id_and_more'),
        ('restaurants', '0002_restaurant_owner_restaurant_idx_restaurants_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='accounts.branchowner'),
        ),
    ]
