# Generated by Django 5.1.6 on 2025-04-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_branch_branch_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='branch_owner',
        ),
    ]
