# Generated by Django 5.1.6 on 2025-06-02 12:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_manage_customers_userrole_pos_system_and_more'),
        ('restaurants', '0004_remove_branch_branch_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'restaurant_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'restaurant_holidays',
            },
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('table_number', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
            ],
            options={
                'db_table': 'restaurant_tables',
            },
        ),
        migrations.CreateModel(
            name='RestaurantZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'restaurant_zones',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_delivery_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_dine_in_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='is_pickup_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='operating_hours',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='branch',
            name='settings',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_logos/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='trial', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['is_active'], name='idx_branches_is_active'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['is_active'], name='idx_restaurants_is_active'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['subscription_status'], name='idx_rest_sub_status'),
        ),
        migrations.AddField(
            model_name='restaurantcategory',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_categories', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='restaurantholiday',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='restauranttable',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.branch'),
        ),
        migrations.AddField(
            model_name='restaurantzone',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='restaurants.branch'),
        ),
        migrations.AlterUniqueTogether(
            name='restaurantcategory',
            unique_together={('restaurant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='restaurantholiday',
            unique_together={('restaurant', 'date')},
        ),
        migrations.AddIndex(
            model_name='restauranttable',
            index=models.Index(fields=['status'], name='idx_tables_status'),
        ),
        migrations.AlterUniqueTogether(
            name='restauranttable',
            unique_together={('branch', 'table_number')},
        ),
        migrations.AlterUniqueTogether(
            name='restaurantzone',
            unique_together={('branch', 'name')},
        ),
    ]
