# Generated by Django 5.1.6 on 2025-06-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurantcategory_restaurantholiday_restauranttable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='kitchen_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='kitchen_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
