# Generated by Django 5.1.6 on 2025-07-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_branch_kitchen_enabled_branch_kitchen_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='operating_hours',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='settings',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
