# Generated by Django 5.1.6 on 2025-03-29 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0002_restaurant_owner_restaurant_idx_restaurants_owner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Walk-in Customer', max_length=255)),
                ('phone', models.CharField(default='N/A', max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('walk-in', 'Walk-in'), ('dining', 'Dining'), ('delivery', 'Delivery')], default='walk-in', max_length=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.branch')),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('loyalty_program_id', models.AutoField(primary_key=True, serialize=False)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('points_redeemed', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_programs', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Loyalty Program',
                'verbose_name_plural': 'Loyalty Programs',
                'db_table': 'loyalty_programs',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['branch_id'], name='idx_customers_branch_id'),
        ),
        migrations.AddIndex(
            model_name='loyaltyprogram',
            index=models.Index(fields=['customer'], name='idx_loyalty_cust'),
        ),
    ]
