# Generated by Django 5.1.6 on 2025-03-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('restaurants', '0002_restaurant_owner_restaurant_idx_restaurants_owner_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='branchowner',
            index=models.Index(fields=['restaurant'], name='idx_branchowners_restaurant_id'),
        ),
        migrations.AddIndex(
            model_name='branchowner',
            index=models.Index(fields=['branch'], name='idx_branchowners_branch_id'),
        ),
    ]
