# Generated by Django 5.1.6 on 2025-04-18 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_branchowner_idx_branchowners_restaurant_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='branchowner',
            name='idx_branchowners_restaurant_id',
        ),
        migrations.RemoveIndex(
            model_name='branchowner',
            name='idx_branchowners_branch_id',
        ),
        migrations.RemoveField(
            model_name='branchowner',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='branchowner',
            name='restaurant',
        ),
    ]
