# Generated by Django 5.1.6 on 2025-04-18 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_branchowner_idx_branchowners_restaurant_id_and_more'),
        ('restaurants', '0004_remove_branch_branch_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchowner',
            name='branch',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='branch_owners', to='restaurants.branch'),
            preserve_default=False,
        ),
    ]
