# Generated by Django 5.1.6 on 2025-04-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_branchowner_branch'),
        ('restaurants', '0004_remove_branch_branch_owner'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='branchowner',
            index=models.Index(fields=['branch'], name='idx_branchowners_branch_id'),
        ),
    ]
