# Generated by Django 5.1.6 on 2025-04-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_branchowner_idx_branchowners_branch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
