# Generated by Django 5.1.6 on 2025-06-16 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_manage_customers_userrole_pos_system_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrole',
            old_name='kitchen_portal_access',
            new_name='kitchen_display',
        ),
    ]
