# Generated by Django 5.1.6 on 2025-07-05 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_rename_kitchen_portal_access_userrole_kitchen_display'),
        ('items', '0001_initial'),
        ('orders', '0001_initial'),
        ('restaurants', '0007_alter_branch_operating_hours_alter_branch_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_orders', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'pos_sessions',
            },
        ),
        migrations.CreateModel(
            name='POSOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('SPLIT', 'Split Payment')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurants.restauranttable')),
                ('pos_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.possession')),
            ],
            options={
                'db_table': 'pos_orders',
            },
        ),
        migrations.CreateModel(
            name='POSOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_void', models.BooleanField(default=False)),
                ('void_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
                ('pos_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_items', to='pos.posorder')),
            ],
            options={
                'db_table': 'pos_order_items',
                'indexes': [models.Index(fields=['pos_order'], name='idx_pos_order_items_order'), models.Index(fields=['is_void'], name='idx_pos_order_items_void')],
            },
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['user', 'is_active'], name='idx_pos_sessions_user_active'),
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['branch'], name='idx_pos_sessions_branch'),
        ),
        migrations.AddConstraint(
            model_name='possession',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'is_active'), name='unique_active_session_per_user'),
        ),
        migrations.AddIndex(
            model_name='posorder',
            index=models.Index(fields=['pos_session'], name='idx_pos_orders_session'),
        ),
        migrations.AddIndex(
            model_name='posorder',
            index=models.Index(fields=['payment_status'], name='idx_pos_orders_payment_status'),
        ),
    ]
