# Generated by Django 5.1.6 on 2025-07-06 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_paid_order_paid_at'),
        ('restaurants', '0007_alter_branch_operating_hours_alter_branch_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurants.restauranttable'),
        ),
    ]
